---
- name: Restart pgpool-II service
  systemd:
    name: "{{ pgpool2_service_name }}"
    state: restarted
  when: use_system_user

- name: Include ensure_pgpool2_process.yml tasks
  include_tasks: ensure_pgpool2_process.yml
  vars:
    - _pgpool2_exists: ""
  when: not use_system_user

- name: Restart pgpool-II process
  when:
    - not use_system_user
    - _pgpool2_exists.rc is defined
    - _pgpool2_exists.rc == 0
  become: true
  become_user: "{{ pgpool2_user }}"
  block:
    - name: Stop pgpool-II process
      command: "{{ pgpool_stop_command }}"
      when: pgpool2_pid_file_exists.stat.exists
      register: pgpool2_stop_output
      changed_when: pgpool2_stop_output.rc == 0
    - name: Restart pgpool-II process
      command: "{{ pgpool_start_command }} -D"
      register: pgpool2_restart_output
      changed_when: pgpool2_restart_output.rc == 0

- name: Wait for port {{ pgpool2_port }}
  wait_for:
    host: 0.0.0.0
    port: "{{ pgpool2_port }}"
    state: started
