---
# Supported list for check
supported_os:
  - CentOS7
  - CentOS8
  - Debian10
  - Debian11
  - Debian12
  - Debian13
  - OracleLinux7
  - OracleLinux8
  - OracleLinux9
  - RedHat8
  - RedHat9
  - Rocky8
  - Rocky9
  - Ubuntu20
  - Ubuntu22

supported_pg_type:
  - PG

supported_pg_version:
  - 14.0
  - 14.1
  - 14.2
  - 14.3
  - 14.4
  - 14.5
  - 14.6
  - 14.7
  - 14.8
  - 15.0
  - 15.1
  - 15.2
  - 15.3
  - 15.4
